# The Site Settings
# © 2017-2019 Cotes Chung
# MIT licensed


# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#--------------------------

  title: 'Kshitiz Anand'

  description: "SMTS @ Athena Health"
  
  # Replace with your domain, e.g. 'https://username.github.io'
  url: 'https://anandkshitiz.github.io/'
  
  author: Kshitiz Anand                  # change to your full name
  
  avatar: 'https://avatars3.githubusercontent.com/u/23467894?s=460&v=4'   # Support network resources.
  
  github:
    username: anandkshitiz             # change to your github username
  
  twitter:
    username: anandkshitiz            # change to your twitter username

  linkedin:
    username: anandkshitiz
  
  social:
    name: Kshitiz Anand                  # it will shows as the copyright owner in Footer
    email: anandkshitiz@gmail.com             # change to your email address
    links:
      # The first element serves as the copyright owner's link
      - https://www.linkedin.com/in/anandkshitiz/
      # - https://twitter.com/anandkshitiz      # change to your twitter homepage
      # - https://github.com/anandkshitiz       # change to your github homepage
      # Uncomment below to add more social links
      # - https://www.facebook.com/username
  
  google_site_verification: google_meta_tag_verification # change to your verification string
  
  #--------------------------
  
  # Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
  timezone: Asia/Kolkata
  
  google_analytics:
    # Fill with your Google Analytics ID
    id: ''
    # The Google Analytics pageviews switch.
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    pv: false
    # superProxy baseURL and URL, only valid when `google_analytics.pv` is set to 'true'
    proxy_baseurl: ''
    proxy_url: ''
  
  
  disqus:
    shortname: 'anandkshitiz'   # Change to your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    comments: true        # boolean type, the global switch for posts comments.
  
  # The year your website was first run.
  first_run: 2019
  
  # boolean type, global switch for ToC in posts.
  toc: true
  
  
  # if your site type is Project Pages site, change below value to '/projectname'
  baseurl: ''
  
  paginate: 10
  
  markdown: kramdown
  
  highlighter: rouge
  
  kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
      css_class: 'highlight'
      # default_lang: console
      span:
        line_numbers: false
      block:
        line_numbers: true
        start_line: 1
  
  permalink: /posts/:title/
  
  defaults:
    -
      scope:
        path: ""          # An empty string here means all files in the project
        type: posts
      values:
        layout: post
        comments: false    # Enable comments in posts.
        toc: true         # Display TOC column in posts.
        location: Post
        breadcrumb:
          -
            label: Posts
            url: /
    -
      scope:
        path: _drafts
      values:
        comments: false
    -
      scope:
        path: tags
      values:
        location: Tag
        breadcrumb:
          -
            label: Home
            url: /
          -
            label: Tags
            url: /tabs/tags/
    -
      scope:
        path: categories
      values:
        location: Category
        breadcrumb:
          -
            label: Home
            url: /
          -
            label: Categories
            url: /tabs/categories/
    -
      scope:
        path: tabs
      values:
        layout: page
        dynamic_title: true    # Hide title in mobile screens.
        breadcrumb:
          -
            label: Home
            url: /
  
  sass:
    sass_dir: /assets/css
    style: compressed
  
  compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: [html, head, body, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
    profile: false
    blanklines: false
    ignore:
      envs: []
  
  exclude:
    - vendor/       # Avoid Jekyll mistakenly read the vender directory on Travis-CI's VM .
    - Gemfile.lock
    - Gemfile
    - run.sh
    - build.sh
    - init.sh
    - pv.sh
  
  sitemap_exclude:  # Sitemap will exclude the following items.
    - /norobots/
    - /assets/
    - /tabs/
    - /categories/
    - /tags/
    - /posts/
    - /404.html
    - /redirects.json
    - /search.json
  